name: miner
description: "miner"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  uuid: ^4.2.2
  get_storage: ^2.0.3
  path_provider: ^2.1.4
  decimal: ^3.0.2
  big_decimal: ^0.5.0
  intl: any
  image: ^4.2.0
  url_launcher: ^6.3.0
  path: ^1.9.0
  country_code_picker: ^3.0.0
  flutter_verification_code: ^1.1.7
  random_x: ^0.3.1
  crypto: ^3.0.6
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.3.2
  dart_ipify: ^1.1.1
  msix: ^3.16.8
  language_picker: ^0.4.5
  dropdown_search: ^6.0.1

msix_config:
  display_name: HASHVAULTPRO
  publisher_display_name: HASHVAULTPRO
  identity_name: com.miner.miner
  msix_version: 1.0.0.0
  logo_path: /var/www/html/works/miner/assets/images/logo.png
  capabilities: internetClient, location


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: [ assets/images/, assets/config/ ]

  fonts: [ ]
  generate: true
