// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEg9rIBpRRcTX7vAPmzzFsoxsCZ8DdkYQ',
    appId: '1:133752152364:web:44568800d6ef96f313cc89',
    messagingSenderId: '133752152364',
    projectId: 'trade-management-app',
    authDomain: 'trade-management-app.firebaseapp.com',
    storageBucket: 'trade-management-app.firebasestorage.app',
    measurementId: 'G-1FX6RK7EWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuq1fgE-oCy82JqYkjdp9ZwYj0ZL-bgxc',
    appId: '1:133752152364:android:01e3f1d3ad33bdb113cc89',
    messagingSenderId: '133752152364',
    projectId: 'trade-management-app',
    storageBucket: 'trade-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARmECms6wsMQApAbv2rH_Pc6c6LazfHDo',
    appId: '1:133752152364:ios:2a7ed6e2b63f59ee13cc89',
    messagingSenderId: '133752152364',
    projectId: 'trade-management-app',
    storageBucket: 'trade-management-app.firebasestorage.app',
    iosBundleId: 'com.miner.miner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARmECms6wsMQApAbv2rH_Pc6c6LazfHDo',
    appId: '1:133752152364:ios:2a7ed6e2b63f59ee13cc89',
    messagingSenderId: '133752152364',
    projectId: 'trade-management-app',
    storageBucket: 'trade-management-app.firebasestorage.app',
    iosBundleId: 'com.miner.miner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEg9rIBpRRcTX7vAPmzzFsoxsCZ8DdkYQ',
    appId: '1:133752152364:web:3598ff1d3e7eb3ad13cc89',
    messagingSenderId: '133752152364',
    projectId: 'trade-management-app',
    authDomain: 'trade-management-app.firebaseapp.com',
    storageBucket: 'trade-management-app.firebasestorage.app',
    measurementId: 'G-C1EGMNG992',
  );
}
